// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$0 from "./sections/Theme.tsx";
import * as $$$$$$1 from "./sections/Footer.tsx";
import * as $$$$$$$$$$$0 from "./apps/site.ts";
import * as $$$$$$$$$$$1 from "./apps/decohub.ts";

const manifest = {
  "sections": {
    "deco-sites/start/sections/Footer.tsx": $$$$$$1,
    "deco-sites/start/sections/Theme.tsx": $$$$$$0,
  },
  "apps": {
    "deco-sites/start/apps/decohub.ts": $$$$$$$$$$$1,
    "deco-sites/start/apps/site.ts": $$$$$$$$$$$0,
  },
  "name": "deco-sites/start",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
